name: Minify

run-name: Minify Code

on:
  push:
    branches: ['main']

permissions:
  contents: write

concurrency:
  group: "minify"
  cancel-in-progress: true

jobs:
  build:
    environment: github-pages
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout ðŸ›Žï¸
        uses: actions/checkout@v3

      - name: Minify Nr. 2
        uses: Lenni009/minify-js@main
        with:
          overwrite: true

      - run: |
          touch .nojekyll
          find . -name "*.md" -type f -delete
          echo "${{ vars.CNAME }}" > CNAME

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: . # The folder the action should deploy.
